// SPDX-License-Identifier: Apache-2.0

// NextAuth v5 — full configuration (Node.js runtime only).
//
// The Edge-compatible `authConfig` (imported from `./auth.config`) carries
// session strategy, callbacks, and the page paths. This file layers on
// the database adapter and providers, so the Edge bundle stays slim.
//
// Splitting like this is the canonical NextAuth v5 pattern: see
// https://authjs.dev/guides/edge-compatibility — the middleware uses the
// bare `authConfig` via `NextAuth(authConfig).auth`, while route handlers
// and server actions use the full config exported here.

import bcrypt from 'bcryptjs';
import { createHmac, timingSafeEqual } from 'node:crypto';
import { and, eq, isNull, sql } from 'drizzle-orm';
import NextAuth from 'next-auth';
import { AuthError } from 'next-auth';
import Credentials from 'next-auth/providers/credentials';
import Google from 'next-auth/providers/google';
import { verifySync } from 'otplib';
import { decryptSecret } from '@hamafx/shared/encryption';
import { authConfig } from './auth.config';
import { schema, withRateLimit } from '@hamafx/db';
import { getDb } from '@hamafx/ai';
import { logErrorContext } from '@hamafx/shared/logger';
import { getAuthEnv } from '@/lib/env';
import { recordAuthEvent } from '@/lib/auth-anomaly';
import { provisionUserOnSignIn } from '@/lib/auth/provision-user';
import { validateSession } from '@/lib/auth/session-validators';

// `NextAuth()` returns a value whose inferred type carries deep paths into
// `@auth/core/providers`. That inferred type isn't portable across pnpm
// store layouts (TS error TS2742). We side-step the portability error by
// typing the destructured exports with the structural shape we need,
// rather than re-naming the inferred type. The @ts-ignore on the right-hand
// side suppresses the only error TS reports; consumers re-narrow as needed.
// See: https://github.com/nextauthjs/next-auth/discussions/9138
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const _nextAuth = NextAuth as any;

const IMPERSONATION_ENABLED =
  process.env.NODE_ENV !== 'production' && process.env.ENABLE_IMPERSONATION === 'true';

const _authEnv = (() => { try { return getAuthEnv(); } catch { return {} as Record<string, string | undefined>; } })();
const GOOGLE_ENABLED =
  !!(_authEnv.AUTH_GOOGLE_ID && _authEnv.AUTH_GOOGLE_SECRET);

/**
 * Known bcrypt hash used for constant-time comparison when no user is found.
 * Prevents timing-based user enumeration (P2-1).
 * Hash of 'dummy-password-for-timing-defense' at cost 12.
 */
const DUMMY_HASH =
  '$2b$12$LyYuAYJhLrPU7mAIQPzVNu5HBJ/neEmE2uZZDD5ayPPROn5ruSaJ2';

// ── H-1: Impersonation challenge verification ────────────────────────

const IMPERSONATION_CHALLENGE_TTL_MS = 30_000; // 30 seconds

/**
 * Generate a signed challenge token that proves the caller has admin
 * privileges. Used by /api/admin/impersonate to authorize the
 * impersonation credentials provider.
 *
 * Format: "<timestamp_hex>.<hmac_hex>"
 */
export function generateImpersonationChallenge(): string {
  const now = Date.now();
  const tsHex = now.toString(16);
  const secret = process.env.AUTH_SECRET || process.env.NEXTAUTH_SECRET;
  if (!secret) throw new Error('AUTH_SECRET is required to generate impersonation challenge');
  const hmac = createHmac('sha256', secret.slice(0, 128))
    .update(`impersonate:${tsHex}`)
    .digest('hex');
  return `${tsHex}.${hmac}`;
}

/**
 * Verify an impersonation challenge token. Returns true only if the
 * token was generated by generateImpersonationChallenge() within the
 * last IMPERSONATION_CHALLENGE_TTL_MS milliseconds.
 */
async function verifyImpersonationChallenge(challenge: string): Promise<boolean> {
  const dot = challenge.indexOf('.');
  if (dot < 1 || dot >= challenge.length - 1) return false;
  const tsHex = challenge.slice(0, dot);
  const sig = challenge.slice(dot + 1);
  const ts = parseInt(tsHex, 16);
  if (!Number.isFinite(ts) || Date.now() - ts > IMPERSONATION_CHALLENGE_TTL_MS) return false;

  const secret = process.env.AUTH_SECRET || process.env.NEXTAUTH_SECRET;
  if (!secret) return false;
  const expected = createHmac('sha256', secret.slice(0, 128))
    .update(`impersonate:${tsHex}`)
    .digest('hex');

  if (expected.length !== sig.length) return false;
  return timingSafeEqual(Buffer.from(expected), Buffer.from(sig));
}

export const { handlers, auth, signIn, signOut } = _nextAuth({
  ...authConfig,
  providers: [
    Credentials({
      name: 'Email + Password',
      credentials: {
        email: { label: 'Email', type: 'email' },
        password: { label: 'Password', type: 'password' },
        totpCode: { label: '2FA Code', type: 'text' },
        rememberMe: { label: 'Remember Me', type: 'text' },
        deviceName: { label: 'Device Name', type: 'text' },
        ip: { label: 'IP Address', type: 'text' },
      },
      async authorize(credentials, _req) {
        const email =
          typeof credentials?.email === 'string' ? credentials.email.toLowerCase().trim() : '';
        const password =
          typeof credentials?.password === 'string' ? credentials.password : '';
        if (!email || !password) return null;

        const db = getDb();

        // ── Step 1: Fetch user (with 2FA fields + lockout state) ──────
        let user: {
          id: string;
          email: string;
          name: string | null;
          image: string | null;
          hashedPassword: string | null;
          tokenVersion: number;
          twoFactorEnabled: boolean;
          twoFactorSecret: string | null;
          lockedUntil: Date | null;
          failedLoginAttempts: number;
          twoFactorBackupCodes: string[] | null;
          failed2faAttempts: number;
          twoFactorLockedUntil: Date | null;
          emailVerified: Date | null;
        } | undefined;
        try {
          [user] = await db
            .select({
              id: schema.users.id,
              email: schema.users.email,
              name: schema.users.name,
              image: schema.users.image,
              hashedPassword: schema.users.hashedPassword,
              tokenVersion: schema.users.tokenVersion,
              twoFactorEnabled: schema.users.twoFactorEnabled,
              twoFactorSecret: schema.users.twoFactorSecret,
          lockedUntil: schema.users.lockedUntil,
          failedLoginAttempts: schema.users.failedLoginAttempts,
          twoFactorBackupCodes: schema.users.twoFactorBackupCodes,
          failed2faAttempts: schema.users.failed2faAttempts,
          twoFactorLockedUntil: schema.users.twoFactorLockedUntil,
          emailVerified: schema.users.emailVerified,
            })
            .from(schema.users)
            .where(and(
              eq(schema.users.email, email),
              isNull(schema.users.deletedAt),
            ))
            .limit(1);
        } catch (err) {
          logErrorContext(err, 'auth/db_fetch_user_failed', {}, 'auth');
          return null; // fail closed on unexpected DB errors
        }

        // ── P2-1: Constant-time fallback when no user / no password ──
        if (!user || !user.hashedPassword) {
          // Run bcrypt against a dummy hash to equalize response time,
          // preventing user-enumeration via timing side-channel.
          await bcrypt.compare(password, DUMMY_HASH);
          return null;
        }

        // ── P0-2: Check lockout (propagates out — NOT caught) ──────────
        if (user.lockedUntil && user.lockedUntil > new Date()) {
          recordAuthEvent('account_locked');
          throw new AuthError('ACCOUNT_LOCKED');
        }

        // ── Step 2: Verify password ────────────────────────────────────
        let passwordValid: boolean;
        try {
          passwordValid = await bcrypt.compare(password, user.hashedPassword);
        } catch (err) {
          logErrorContext(err, 'auth/bcrypt_error', {}, 'auth');
          return null; // fail closed on unexpected bcrypt errors
        }

        if (!passwordValid) {
          // ── P2-2: Atomic SQL increment (no read-modify-write race) ──
          try {
            await db
              .update(schema.users)
              .set({
                failedLoginAttempts: sql`${schema.users.failedLoginAttempts} + 1`,
                lockedUntil: sql`CASE WHEN ${schema.users.failedLoginAttempts} + 1 >= 5 THEN NOW() + INTERVAL '15 minutes' ELSE NULL END`,
              })
              .where(eq(schema.users.id, user.id));
          } catch {
            /* fail open — lockout is best-effort; DB may be unavailable */
            logErrorContext(
              new Error('Failed to increment failed login attempts'),
              'auth/lockout_increment',
              { userId: user.id },
              'auth',
            );
          }
          return null;
        }

        // ── Reset lockout counter on successful password ───────────────
        try {
          await db
            .update(schema.users)
            .set({ failedLoginAttempts: 0, lockedUntil: null })
            .where(eq(schema.users.id, user.id));
        } catch {
          /* fail open — reset is best-effort */
          logErrorContext(
            new Error('Failed to reset lockout counter'),
            'auth/lockout_reset',
            { userId: user.id },
            'auth',
          );
        }

        // ── P0-1 / P2-6: Enforce 2FA at login with backup-code fallback ─────────────────────────────────
        if (user.twoFactorEnabled) {
          const totpCode =
            typeof credentials?.totpCode === 'string'
              ? credentials.totpCode.trim()
              : '';
          if (!totpCode) {
            throw new AuthError('2FA_REQUIRED');
          }

          // P2-6: dedicated 2FA lockout
          if (user.twoFactorLockedUntil && user.twoFactorLockedUntil > new Date()) {
            throw new AuthError('2FA_LOCKED');
          }

          // P2-6: per-user 2FA rate limit (separate from login rate limits)
          let rateLimitAllowed = true;
          try {
            const rl2fa = await withRateLimit(user.id, '2fa_verify', 10);
            rateLimitAllowed = rl2fa.allowed;
          } catch {
            // withRateLimit may throw on DB outage — fail open to avoid
            // locking users out when the DB is unavailable.
          }
          if (!rateLimitAllowed) {
            throw new AuthError('2FA_RATE_LIMITED');
          }

          const secret = user.twoFactorSecret
            ? decryptSecret(user.twoFactorSecret)
            : null;

          let valid2FA = false;

          if (secret && verifySync({ secret, token: totpCode }).valid) {
            valid2FA = true;
          } else if (user.twoFactorBackupCodes && user.twoFactorBackupCodes.length > 0) {
            // P2-6: fallback to single-use backup codes
            const hashedCodes = user.twoFactorBackupCodes;
            for (const hashed of hashedCodes) {
              if (await bcrypt.compare(totpCode, hashed)) {
                valid2FA = true;
                // Consume the single-use backup code.
                try {
                  const remaining = user.twoFactorBackupCodes!.filter((h) => h !== hashed);
                  await db
                    .update(schema.users)
                    .set({ twoFactorBackupCodes: remaining })
                    .where(eq(schema.users.id, user.id));
                } catch (err) {
                  logErrorContext(err, 'auth/consume_backup_code', { userId: user.id }, 'auth');
                }
                break;
              }
            }
          }

          if (!valid2FA) {
            recordAuthEvent('2fa_failure');
            // P2-6: increment failed 2FA attempts and lock after 5
            try {
              await db
                .update(schema.users)
                .set({
                  failed2faAttempts: sql`${schema.users.failed2faAttempts} + 1`,
                  twoFactorLockedUntil:
                    sql`CASE WHEN ${schema.users.failed2faAttempts} + 1 >= 5 THEN NOW() + INTERVAL '15 minutes' ELSE NULL END`,
                })
                .where(eq(schema.users.id, user.id));
            } catch (err) {
              logErrorContext(err, 'auth/2fa_lockout_increment', { userId: user.id }, 'auth');
            }
            throw new AuthError('INVALID_2FA_CODE');
          }

          // Reset 2FA failure counter on success
          try {
            await db
              .update(schema.users)
              .set({ failed2faAttempts: 0, twoFactorLockedUntil: null })
              .where(eq(schema.users.id, user.id));
          } catch (err) {
            logErrorContext(err, 'auth/2fa_lockout_reset', { userId: user.id }, 'auth');
          }
        }

        // ── P0-3: Read rememberMe from credentials ─────────────────────
        const rememberMe = credentials?.rememberMe === 'true';

        // ── P0-4: Generate sessionId + capture device info ──────────
        const sessionId = crypto.randomUUID();
        const deviceName =
          typeof credentials?.deviceName === 'string'
            ? credentials.deviceName.slice(0, 255) || null
            : null;
        const ip =
          typeof credentials?.ip === 'string'
            ? credentials.ip || null
            : null;

        return {
          id: user.id,
          email: user.email,
          name: user.name,
          image: user.image,
          tokenVersion: user.tokenVersion,
          emailVerified: user.emailVerified,
          sessionId,
          deviceName,
          ip,
          rememberMe,
        };
      },
    }),
    // P1-2: Google OAuth — conditional on env vars so self-hosters
    // without Google keys are unaffected.
    ...(GOOGLE_ENABLED
      ? [
          Google({
            clientId: _authEnv.AUTH_GOOGLE_ID!,
            clientSecret: _authEnv.AUTH_GOOGLE_SECRET!,
            allowDangerousEmailAccountLinking: false, // we link explicitly in signIn
          }),
        ]
      : []),
    // Dev-only impersonation provider. Only registered when ENABLE_IMPERSONATION
    // is set and not in production. This provider bypasses password checks
    // so an admin can sign in as another user for debugging.
    //
    // H-1: The provider verifies a signed admin challenge token before
    // authorizing impersonation. The /api/admin/impersonate route
    // (protected by withAdminAuth) generates this token. Direct calls
    // to the impersonation provider without a valid token are rejected.
    ...(IMPERSONATION_ENABLED
      ? [
          Credentials({
            id: 'impersonate',
            name: 'Impersonation',
            credentials: {
              userId: { label: 'User ID', type: 'text' },
              challenge: { label: 'Admin Challenge Token', type: 'text' },
            },
            async authorize(credentials) {
              const userId = typeof credentials?.userId === 'string' ? credentials.userId : '';
              const challenge = typeof credentials?.challenge === 'string' ? credentials.challenge : '';
              if (!userId || !challenge) return null;

              // H-1: Verify the admin-signed challenge token. Only the
              // /api/admin/impersonate route (protected by withAdminAuth)
              // can generate a valid token. This prevents anyone from
              // calling the impersonation provider directly to escalate.
              const valid = await verifyImpersonationChallenge(challenge);
              if (!valid) {
                logErrorContext(
                  new Error('Impersonation challenge verification failed'),
                  'auth/impersonation_challenge',
                  { userId },
                  'auth',
                );
                return null;
              }

              const db = getDb();
              const [user] = await db
                .select()
                .from(schema.users)
                .where(eq(schema.users.id, userId))
                .limit(1);

              if (!user) return null;

              return {
                id: user.id,
                email: user.email,
                name: user.name,
                image: user.image,
                tokenVersion: user.tokenVersion,
                sessionId: '',
                rememberMe: false,
              };
            },
          }),
        ]
      : []),
  ],
  callbacks: {
    ...authConfig.callbacks,
    /**
     * P1-2 / §4.3: Provision DB rows for Google OAuth sign-ins.
     * Links existing Credentials users by email; creates new user +
     * user_settings for first-time Google sign-ins. Google emails are
     * pre-verified so emailVerified is set automatically.
     */
    // SRP-3: signIn callback delegates provisioning + account linking to
    // provisionUserOnSignIn (typed, testable). The callback stays thin glue.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    async signIn({ user, account, profile }: { user: any; account: any; profile: any }) {
      const decision = await provisionUserOnSignIn({ user, account, profile });
      if (!decision.allow) return false;

      // Merge DB identity fields onto the user object so JWT callback uses them
      if (decision.userFields) {
        user.id = decision.userFields.id;
        user.tokenVersion = decision.userFields.tokenVersion;
        user.emailVerified = decision.userFields.emailVerified;
        user.rememberMe = decision.userFields.rememberMe;
        user.sessionId = decision.userFields.sessionId;
      }

      return true;
    },
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    async jwt({ token, user }: { token: any; user: any }) {
      if (user) {
        token.id = user.id;
        token.tokenVersion = user.tokenVersion ?? 0;
        token.emailVerified = user.emailVerified ?? null;
        token.rememberMe = user.rememberMe === true ? true : undefined;

        // P0-4: Create user_sessions row on first JWT mint.
        // tenantId has a DB-side SQL default; not passing it here
        // so Postgres applies current_setting('app.current_tenant', true).
        const sessionId = user.sessionId || crypto.randomUUID();
        token.sessionId = sessionId;
        try {
          const db = getDb();
          await db.execute(
            sql`INSERT INTO ${schema.userSessions} (id, user_id, device_name, ip)
                VALUES (${sessionId}, ${user.id}, ${(user.deviceName as string) ?? null}, ${(user.ip as string) ?? null})`,
          );
        } catch {
          /* fail open — session insert is best-effort */
          logErrorContext(
            new Error('Failed to create user session'),
            'auth/session_insert',
            { userId: user.id, sessionId },
            'auth',
          );
        }
      }
      if (token.tokenVersion === undefined) {
        token.tokenVersion = 0;
      }
      return token;
    },
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    async session({ session, token }: { session: any; token: any }) {
      if (session.user && token.id) {
        session.user.id = token.id;
      }
      // P0-5: expose emailVerified on session for soft enforcement
      if (token.emailVerified !== undefined) {
        session.user.emailVerified = token.emailVerified;
      }
      if (token.sessionId) {
        session.sessionId = token.sessionId;
      }
      const now = Math.floor(Date.now() / 1000);

      let db;
      try {
        db = getDb();
      } catch {
        // DB unavailable — keep the session alive rather than locking the user out.
        return session;
      }

      const invalidated = await validateSession(db, token, session, now, { failClosed: false });
      if (invalidated) {
        return invalidated;
      }

      return session;
    },
  },
});

