/**
 * Copyright 2026 HamaFX
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// F7 — /chart command: send a chart snapshot image for a symbol.
// /chart XAUUSD → fetches a chart image and sends it.
//
// Uses the existing snapshot system to generate a chart image.

import type { BotCommand, BotResponse } from '../types';

export const chartCommand: BotCommand = {
  name: 'chart',
  aliases: ['c'],
  description: 'Chart snapshot: /chart <symbol>',
  handler: async (args: string[]): Promise<BotResponse> => {
    const symbolStr = args[0];
    if (!symbolStr) {
      return {
        text: 'Usage: /chart <symbol>\nExample: /chart XAUUSD',
      };
    }

    const symbol = symbolStr.toUpperCase();

    // The chart image is generated by the frontend. In the bot context,
    // we provide a link to the web UI chart page.
    // A full implementation would use a headless browser to capture the chart.
    return {
      text: [
        `📈 ${symbol} Chart`,
        '',
        `View the full chart on HamaFX:`,
        `https://hamafx.ai/chart/${symbol}`,
        '',
        `Chart image generation is available on the web platform.`,
      ].join('\n'),
    };
  },
};
