#!/usr/bin/env bash
# docker/init-secrets.sh — Generate random secrets for Docker deployment.
#
# Creates a .env file in the repo root with cryptographically random values
# for all required secrets. Safe to re-run — existing .env is never overwritten.
#
# Usage:
#   ./docker/init-secrets.sh
#   docker compose up -d

set -euo pipefail

ENV_FILE="$(cd "$(dirname "$0")/.." && pwd)/.env"

if [[ -f "$ENV_FILE" ]]; then
  echo "✓ .env already exists — leaving it untouched."
  echo "  To regenerate, delete it first: rm .env"
  exit 0
fi

# Generate a random hex string of the given byte length.
rand_hex() {
  local bytes="${1:-32}"
  node -e "console.log(require('crypto').randomBytes($bytes).toString('hex'))"
}

cat > "$ENV_FILE" <<EOF
# HamaFX-Ai Docker deployment secrets
# Generated by docker/init-secrets.sh on $(date -u +%FT%TZ)
# DO NOT commit this file — it is already in .gitignore.

# ── Postgres ──────────────────────────────────────────────
POSTGRES_PASSWORD=$(rand_hex 16)

# ── Local Docker backups ─────────────────────────────────
# Backups remain on the named backup-data volume by default. These are
# operational settings, not secrets, but keeping them in .env makes the
# retention policy visible and easy to override.
BACKUP_INTERVAL_SECONDS=86400
BACKUP_RETENTION_DAYS=7
BACKUP_MAX_AGE_SECONDS=172800

# ── Langfuse (LLM observability) ──────────────────────────
LANGFUSE_NEXTAUTH_SECRET=$(rand_hex 32)
LANGFUSE_SALT=$(rand_hex 16)

# ── NextAuth (app authentication) ─────────────────────────
AUTH_SECRET=$(rand_hex 32)
NEXTAUTH_URL=http://localhost:3000

# ── Cron authentication ────────────────────────────────────
CRON_SECRET=$(rand_hex 16)

# ── Encryption (BYOK key encryption at rest) ──────────────
ENCRYPTION_SECRET=$(rand_hex 32)

# ── Safe self-hosted defaults ──────────────────────────────
BYOK_ENABLED=1
MULTI_USER_ENABLED=0
REGISTRATION_MODE=owner-first
HAMAFX_ENABLE_RLS=0
EOF

chmod 600 "$ENV_FILE"
echo "✓ Generated .env with random secrets."
echo "  Review it:  cat .env"
echo "  Now run:    docker compose up -d"
echo "  Optional:   docker compose --profile observability up -d"
