#!/usr/bin/env bash
# docker/init-secrets.sh — Generate random secrets for Docker deployment.
#
# Creates a .env file in the repo root with cryptographically random values
# for all required secrets. Safe to re-run — existing .env is never overwritten.
#
# Usage:
#   ./docker/init-secrets.sh
#   docker compose up -d

set -euo pipefail

ENV_FILE="$(cd "$(dirname "$0")/.." && pwd)/.env"

if [[ -f "$ENV_FILE" ]]; then
  echo "✓ .env already exists — leaving it untouched."
  echo "  To regenerate, delete it first: rm .env"
  exit 0
fi

# Generate a random hex string of the given byte length.
rand_hex() {
  local bytes="${1:-32}"
  node -e "console.log(require('crypto').randomBytes($bytes).toString('hex'))"
}

cat > "$ENV_FILE" <<EOF
# HamaFX-Ai Docker deployment secrets
# Generated by docker/init-secrets.sh on $(date -u +%FT%TZ)
# DO NOT commit this file — it is already in .gitignore.

# ── Postgres ──────────────────────────────────────────────
POSTGRES_PASSWORD=$(rand_hex 16)

# ── Langfuse (LLM observability) ──────────────────────────
LANGFUSE_NEXTAUTH_SECRET=$(rand_hex 32)
LANGFUSE_SALT=$(rand_hex 16)

# ── NextAuth (app authentication) ─────────────────────────
NEXTAUTH_SECRET=$(rand_hex 32)
NEXTAUTH_URL=http://localhost:3000

# ── Encryption (BYOK key encryption at rest) ──────────────
ENCRYPTION_SECRET=$(rand_hex 32)
EOF

chmod 600 "$ENV_FILE"
echo "✓ Generated .env with random secrets."
echo "  Review it:  cat .env"
echo "  Now run:    docker compose up -d"
