/**
 * Copyright 2026 HamaFX
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Chat persistence: load / save thread + messages, write per-turn telemetry.
// Anything that touches Postgres lives here so route handlers stay thin.

import { getDb, schema } from '@hamafx/db';
import type { Symbol } from '@hamafx/shared';
import type { ModelMessage, UIMessage } from 'ai';
import { and, asc, desc, eq, lt } from 'drizzle-orm';

import { estimateCostUsd } from './cost';

// ---------------------------------------------------------------------------
// Threads
// ---------------------------------------------------------------------------

export interface DbThread {
  id: string;
  title: string | null;
  /**
   * Provenance of `title`: `'llm'` = produced by `Title_Generator`,
   * `'fallback'` = deterministic local fallback, `null` = legacy row created
   * before the `title_source` column existed.
   */
  titleSource: 'llm' | 'fallback' | null;
  pinnedSymbol: Symbol | null;
  modelOverride: string | null;
  createdAt: number;
  updatedAt: number;
}

export async function listThreads(
  userId: string,
  limit = 50,
  // PERF-07: Cursor-based pagination using updatedAt.
  // Pass the `updatedAt` of the last item from the previous page to get the
  // next page. Cursor is an ISO string or epoch ms; null = first page.
  beforeUpdatedAt?: number | null,
): Promise<{ threads: DbThread[]; nextCursor: number | null }> {
  const query = getDb()
    .select()
    .from(schema.chatThreads)
    .where(
      beforeUpdatedAt
        ? and(
            eq(schema.chatThreads.userId, userId),
            lt(schema.chatThreads.updatedAt, new Date(beforeUpdatedAt)),
          )
        : eq(schema.chatThreads.userId, userId),
    )
    .orderBy(desc(schema.chatThreads.updatedAt))
    // Fetch one extra to know if there's a next page.
    .limit(limit + 1);

  const rows = await query;
  const hasMore = rows.length > limit;
  const pageRows = hasMore ? rows.slice(0, limit) : rows;
  const threads = pageRows.map(rowToThread);
  const nextCursor = hasMore ? (threads[threads.length - 1]?.updatedAt ?? null) : null;
  return { threads, nextCursor };
}

export async function getThread(userId: string, id: string): Promise<DbThread | null> {
  // Phase B — IDOR fix. Filter on (id, userId) so a logged-in user can
  // never read another user's thread, even if they guess the UUID.
  const rows = await getDb()
    .select()
    .from(schema.chatThreads)
    .where(and(eq(schema.chatThreads.id, id), eq(schema.chatThreads.userId, userId)))
    .limit(1);
  const row = rows[0];
  return row ? rowToThread(row) : null;
}

export async function createThread(
  userId: string,
  opts: { pinnedSymbol?: Symbol | null } = {},
): Promise<DbThread> {
  const inserted = await getDb()
    .insert(schema.chatThreads)
    .values({
      userId,
      title: null,
      pinnedSymbol: opts.pinnedSymbol ?? null,
      modelOverride: null,
    })
    .returning();
  const row = inserted[0]!;
  return rowToThread(row);
}

/**
 * Persist a thread title together with its provenance.
 *
 * `source` is required so we can never accidentally drop the discriminator
 * that powers the auto-title telemetry/UX (`'llm'` = generated by
 * `Title_Generator`, `'fallback'` = deterministic local fallback). Both
 * columns are written in one UPDATE to keep them consistent.
 */
export async function updateThreadTitle(
  id: string,
  title: string,
  source: 'llm' | 'fallback',
): Promise<void> {
  await getDb()
    .update(schema.chatThreads)
    .set({ title, titleSource: source })
    .where(eq(schema.chatThreads.id, id));
}

/**
 * Set or clear the pinnedSymbol on a thread.
 *
 * Phase A — UX_UPGRADE_PLAN.md item 1. Scoped by userId so a caller
 * can never mutate another user's thread, even if they hold a valid
 * session and guess the UUID. Returns true when a row was updated,
 * false when the thread does not exist or is not owned by userId
 * (the route handler maps the false case to a 404).
 */
export async function updateThreadPinnedSymbol(
  userId: string,
  id: string,
  pinnedSymbol: Symbol | null,
): Promise<boolean> {
  const updated = await getDb()
    .update(schema.chatThreads)
    .set({ pinnedSymbol, updatedAt: new Date() })
    .where(and(eq(schema.chatThreads.id, id), eq(schema.chatThreads.userId, userId)))
    .returning({ id: schema.chatThreads.id });
  return updated.length > 0;
}

export async function deleteThread(userId: string, id: string): Promise<void> {
  // Phase B — IDOR fix. Filter on userId so a user can only delete
  // their own threads.
  await getDb()
    .delete(schema.chatThreads)
    .where(and(eq(schema.chatThreads.id, id), eq(schema.chatThreads.userId, userId)));
}

export async function deleteAllThreads(userId: string): Promise<void> {
  await getDb()
    .delete(schema.chatThreads)
    .where(eq(schema.chatThreads.userId, userId));
}

function rowToThread(row: typeof schema.chatThreads.$inferSelect): DbThread {
  // `title_source` is a free-text column at the DB layer; narrow it here so
  // every consumer sees the canonical `'llm' | 'fallback' | null` union.
  const rawSource = row.titleSource;
  const titleSource: DbThread['titleSource'] =
    rawSource === 'llm' || rawSource === 'fallback' ? rawSource : null;
  return {
    id: row.id,
    title: row.title,
    titleSource,
    pinnedSymbol: row.pinnedSymbol as Symbol | null,
    modelOverride: row.modelOverride,
    createdAt: row.createdAt.getTime(),
    updatedAt: row.updatedAt.getTime(),
  };
}

// ---------------------------------------------------------------------------
// Messages
// ---------------------------------------------------------------------------

export interface DbMessage {
  id: string;
  threadId: string;
  role: 'user' | 'assistant' | 'system' | 'tool';
  content: string;
  /** Vercel AI SDK v5 message-parts JSON (tool calls, tool results, etc.). */
  parts: unknown;
  createdAt: number;
}

export async function listMessages(userId: string, threadId: string, limit = 200): Promise<DbMessage[]> {
  // Phase B — IDOR fix. Verify the thread belongs to the user before
  // returning any messages.
  const thread = await getThread(userId, threadId);
  if (!thread) return [];
  const rows = await getDb()
    .select()
    .from(schema.chatMessages)
    .where(eq(schema.chatMessages.threadId, threadId))
    .orderBy(asc(schema.chatMessages.createdAt))
    .limit(limit);
  return rows.map((r) => ({
    id: r.id,
    threadId: r.threadId,
    role: r.role as DbMessage['role'],
    content: r.content,
    parts: r.parts,
    createdAt: r.createdAt.getTime(),
  }));
}

export async function appendUserMessage(threadId: string, message: UIMessage): Promise<void> {
  const text = extractText(message);
  // Phase 1 hardening §9 — a connection drop between the INSERT and the
  // sidebar-touching UPDATE used to leave the message persisted while
  // the thread's `updatedAt` stayed stale, which broke sidebar sort.
  // Wrap the pair in a transaction so either both writes land or both
  // roll back.
  await getDb().transaction(async (tx) => {
    await tx.insert(schema.chatMessages).values({
      threadId,
      role: 'user',
      content: text,
      parts: stripPartsForStorage(message.parts ?? null),
    });
    await tx
      .update(schema.chatThreads)
      .set({ updatedAt: new Date() })
      .where(eq(schema.chatThreads.id, threadId));
  });
}

export async function appendAssistantMessage(
  threadId: string,
  message: UIMessage,
): Promise<{ messageId: string }> {
  const text = extractText(message);
  // Phase 1 hardening §9 — same transactional pairing as the user-side
  // helper above. The sidebar sort cares about `updatedAt`, and the
  // telemetry caller relies on the returned `messageId` to attach
  // post-finish metrics.
  return getDb().transaction(async (tx) => {
    const inserted = await tx
      .insert(schema.chatMessages)
      .values({
        threadId,
        role: 'assistant',
        content: text,
        parts: stripPartsForStorage(message.parts ?? null),
      })
      .returning({ id: schema.chatMessages.id });
    await tx
      .update(schema.chatThreads)
      .set({ updatedAt: new Date() })
      .where(eq(schema.chatThreads.id, threadId));
    return { messageId: inserted[0]!.id };
  });
}

// -----------------------------------------------------------------------
// Phase C — UX_UPGRADE_PLAN.md item 19. Fork semantics.
//
// "Edit a non-last user message" creates a NEW thread (fork) at the
// edit point, leaving the original thread untouched. This is the
// conventional AI chat UX (ChatGPT, Claude) and prevents the
// truncation problem: rewriting the message in place would orphan
// all later assistant messages that referenced it.
//
// Algorithm:
//   1. Fetch source thread (scoped by userId — IDOR guard).
//   2. Fetch all source messages.
//   3. Create a new thread with the same `pinnedSymbol` and a
//      auto-generated title based on the new first user message.
//   4. Insert into the new thread all source messages UP TO AND
//      INCLUDING `atMessageId`, replacing that message's text
//      with `newText`.
//   5. Return the new thread id.
//
// The original thread is never mutated. The caller can then
// stream a fresh assistant response from the new thread.
// -----------------------------------------------------------------------

/**
 * Pure helper that builds the new thread's first-message title.
 *
 * The AI chat UX convention is to use the first user message as the
 * thread title. After a fork, the title is the EDITED message (the
 * new text), which usually makes more sense than the original.
 *
 * Truncated to 80 chars with a trailing ellipsis if needed.
 */
export function deriveForkedTitle(newText: string): string {
  const trimmed = newText.trim();
  if (trimmed.length === 0) return 'New chat';
  if (trimmed.length <= 80) return trimmed;
  return trimmed.slice(0, 79).trimEnd() + '…';
}

export interface ForkThreadInput {
  userId: string;
  sourceThreadId: string;
  /**
   * ID of the user message to edit (must be role='user' and belong
   * to the source thread).
   */
  atMessageId: string;
  /** The new text to put at that message. */
  newText: string;
}

export interface ForkThreadResult {
  /** ID of the newly-created thread. */
  newThreadId: string;
  /** The first message in the new thread (with the replaced text). */
  firstMessage: { id: string; role: 'user'; content: string };
}

/**
 * Fork a thread at a user message. Returns the new thread id.
 *
 * Throws when:
 *   - Source thread not found (or not owned by the user).
 *   - `atMessageId` doesn't belong to the source thread.
 *   - `atMessageId` is not a user-role message (only user messages
 *     are editable; clicking the edit icon on an assistant message
 *     is currently a no-op in the UI).
 */
export async function forkThread(input: ForkThreadInput): Promise<ForkThreadResult> {
  const { userId, sourceThreadId, atMessageId, newText } = input;

  // 1) Fetch the source thread. IDOR-checked: scoped by userId.
  const [source] = await getDb()
    .select()
    .from(schema.chatThreads)
    .where(and(eq(schema.chatThreads.id, sourceThreadId), eq(schema.chatThreads.userId, userId)))
    .limit(1);
  if (!source) {
    throw new Error(`thread not found: ${sourceThreadId}`);
  }

  // 2) Fetch all source messages in chronological order.
  const sourceMessages = await getDb()
    .select()
    .from(schema.chatMessages)
    .where(eq(schema.chatMessages.threadId, sourceThreadId))
    .orderBy(asc(schema.chatMessages.createdAt));

  // 3) Find the edit point. The message must be a user message.
  const editIdx = sourceMessages.findIndex((m) => m.id === atMessageId);
  if (editIdx === -1) {
    throw new Error(`message not found: ${atMessageId}`);
  }
  const target = sourceMessages[editIdx]!;
  if (target.role !== 'user') {
    throw new Error(`can only edit user messages, got role=${target.role}`);
  }

  // 4) Build the new thread + the messages it should contain, in a
  //    single transaction so a partial fork never lands.
  const newTitle = deriveForkedTitle(newText);
  return getDb().transaction(async (tx) => {
    const [created] = await tx
      .insert(schema.chatThreads)
      .values({
        userId,
        title: newTitle,
        pinnedSymbol: source.pinnedSymbol ?? null,
      })
      .returning({ id: schema.chatThreads.id });
    const newThreadId = created!.id;

    // 5) Insert all source messages UP TO AND INCLUDING the edit
    //    point. For the edit message, replace the text content but
    //    preserve any non-text parts (e.g. attachments the user
    //    uploaded — we strip text-only attachments but keep image
    //    URLs, since the user said "edit the text" not "edit the
    //    attachments"). For all other messages we copy verbatim.
    const cut = sourceMessages.slice(0, editIdx + 1);
    const insertedIds: string[] = [];
    for (let i = 0; i < cut.length; i++) {
      const m = cut[i]!;
      const isEditPoint = i === editIdx;
      const newContent = isEditPoint ? newText : m.content;
      // For the edit point we keep attachments/parts from the
      // original message so an attached chart image still works.
      const parts = isEditPoint ? m.parts : m.parts;
      const [row] = await tx
        .insert(schema.chatMessages)
        .values({
          threadId: newThreadId,
          role: m.role,
          content: newContent,
          parts: parts ?? null,
          createdAt: m.createdAt,
        })
        .returning({ id: schema.chatMessages.id, role: schema.chatMessages.role, content: schema.chatMessages.content });
      insertedIds.push(row!.id);
    }
    await tx
      .update(schema.chatThreads)
      .set({ updatedAt: new Date() })
      .where(eq(schema.chatThreads.id, newThreadId));

    return {
      newThreadId,
      firstMessage: {
        id: insertedIds[0]!,
        role: 'user' as const,
        content: newText,
      },
    };
  });
}

/**
 * Phase 3 hardening §21 — strip oversize fields before persisting the
 * `parts` JSONB. The model's `tool-result` parts can balloon when a
 * tool returns a base64 image (`analyze_chart_image` re-runs on the
 * user's attachment) or a long candle window. Trimming the obvious
 * offenders keeps the per-row size bounded so the chat sidebar
 * `SELECT *` query stays cheap and the JSON column doesn't grow into
 * the multi-MB range.
 *
 * Strategy: for each `tool-result` part, replace any field on
 * `output` whose name matches a known offender with `'[stripped]'`.
 * We don't try to recurse — the targets are flat keys today, and a
 * recursive walker would slow this hot path for marginal benefit.
 */
const STRIP_FIELDS: ReadonlySet<string> = new Set([
  // Base64 image payloads from analyze_chart_image / share_snapshot.
  'imageDataUrl',
  'image',
  'data',
  // Whole candle windows from analyze_technical / annotate_chart —
  // useful to the model in-flight, not useful in the persisted history.
  'candles',
  // Raw response bodies a tool may have buffered for debugging.
  'rawResponse',
]);

function stripPartsForStorage(parts: unknown): unknown {
  if (!Array.isArray(parts)) return parts;
  return parts.map((p) => {
    if (
      p === null ||
      typeof p !== 'object' ||
      !('type' in (p as Record<string, unknown>))
    ) {
      return p;
    }
    const part = p as { type: unknown; output?: unknown };
    if (part.type !== 'tool-result' || typeof part.output !== 'object' || part.output === null) {
      return p;
    }
    const output = part.output as Record<string, unknown>;
    let modified = false;
    const next: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(output)) {
      if (STRIP_FIELDS.has(k)) {
        next[k] = '[stripped]';
        modified = true;
        continue;
      }
      next[k] = v;
    }
    return modified ? { ...part, output: next } : p;
  });
}

/** Best-effort plain-text extraction from a UIMessage — used for search/title. */
function extractText(m: UIMessage): string {
  const parts = m.parts ?? [];
  const fromParts = parts
    .map((p) => {
      if (typeof p === 'object' && p !== null && 'type' in p) {
        if ((p as { type: string }).type === 'text') {
          return ((p as { text?: string }).text ?? '').trim();
        }
      }
      return '';
    })
    .filter(Boolean)
    .join('\n')
    .trim();
  
  if (fromParts) return fromParts;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return ((m as any).content || (m as any).text || '').trim();
}

// ---------------------------------------------------------------------------
// Telemetry
// ---------------------------------------------------------------------------

export interface TelemetryInput {
  threadId: string;
  /** Phase A — the owning user. */
  userId?: string | null;
  messageId: string | null;
  model: string;
  inputTokens: number;
  outputTokens: number;
  toolCalls: number;
  ms: number;
  /**
   * Row marker for non-assistant-turn telemetry. Legacy assistant-turn callers
   * omit this and the column stays `null`. Title_Generator emits one of:
   * `'title_generated' | 'title_failed' | 'title_skipped_budget'`. The Phase
   * 7a router emits `'routing_<domain>'`. The Phase 7c planner emits one of:
   * `'plan_generated' | 'plan_skipped_budget' | 'plan_failed'`.
   */
  kind?:
    | 'title_generated'
    | 'title_failed'
    | 'title_skipped_budget'
    | 'routing_fundamental'
    | 'routing_technical'
    | 'routing_summary'
    | 'routing_vision'
    | 'routing_generic'
    | 'plan_generated'
    | 'plan_skipped_budget'
    | 'plan_failed';
}

export async function recordTelemetry(t: TelemetryInput): Promise<void> {
  await getDb()
    .insert(schema.chatTelemetry)
    .values({
      userId: t.userId ?? '__system__',
      threadId: t.threadId,
      messageId: t.messageId,
      model: t.model,
      inputTokens: t.inputTokens,
      outputTokens: t.outputTokens,
      toolCalls: t.toolCalls,
      ms: t.ms,
      estCostUsd: estimateCostUsd(t.model, t.inputTokens, t.outputTokens),
      kind: t.kind ?? null,
    });
}

// Re-export so route handlers don't need to import directly from `ai`.
export type { ModelMessage, UIMessage };


// ---------------------------------------------------------------------------
// Per-tool telemetry (Phase 7b)
// ---------------------------------------------------------------------------

export interface ToolTelemetryInput {
  threadId: string | null;
  /** Phase A — the owning user. */
  userId?: string | null;
  messageId: string | null;
  tool: string;
  ms: number;
  ok: boolean;
  errorCode?: string | null;
}

export async function recordToolTelemetry(t: ToolTelemetryInput): Promise<void> {
  try {
    await getDb()
      .insert(schema.chatToolTelemetry)
      .values({
        userId: t.userId ?? '__system__',
        threadId: t.threadId,
        messageId: t.messageId,
        tool: t.tool,
        ms: t.ms,
        ok: t.ok,
        errorCode: t.errorCode ?? null,
      });
  } catch (err) {
    // Tool-telemetry failures must never crash a chat turn.
    console.warn('[ai] tool telemetry insert failed', err);
  }
}
