'use client';

/**
 * Copyright 2026 HamaFX
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// 2.3 — AI trade review panel for closed journal entries.
// Lives in the analytics tab and lets the user request a post-trade review
// for any closed trade. The review is streamed from /api/journal/review.

import type { JournalEntry } from '@hamafx/shared';
import { Sparkles, AlertCircle, RefreshCw } from 'lucide-react';
import { useState } from 'react';

import { Button } from '@/components/ui/button';
import { fetchCsrf } from '@/lib/csrf';
import { cn } from '@/lib/cn';

interface TradeReviewResponse {
  review: {
    review: string;
    modelId: string;
    inputTokens: number;
    outputTokens: number;
    costUsd: number;
    latencyMs: number;
  };
}

interface AiReviewPanelProps {
  entry: JournalEntry;
}

export function AiReviewPanel({ entry }: AiReviewPanelProps) {
  const [review, setReview] = useState<string | null>(null);
  const [modelId, setModelId] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function generateReview() {
    setLoading(true);
    setError(null);
    try {
      const res = await fetchCsrf('/api/journal/review', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ id: entry.id }),
      });
      const body = (await res.json()) as { error?: { message: string } } | TradeReviewResponse;
      if (!res.ok) {
        throw new Error(
          'error' in body && body.error?.message
            ? body.error.message
            : `HTTP ${res.status}`,
        );
      }
      const data = body as TradeReviewResponse;
      setReview(data.review.review);
      setModelId(data.review.modelId);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Review failed');
    } finally {
      setLoading(false);
    }
  }

  if (entry.outcome === 'open') {
    return (
      <div className="rounded-sm border border-zinc-800 bg-zinc-950 p-4 flex items-start gap-3 text-fg-subtle">
        <AlertCircle className="size-5 shrink-0 mt-0.5" />
        <p className="text-sm">
          Close this trade to unlock an AI-powered post-trade review.
        </p>
      </div>
    );
  }

  return (
    <div className="rounded-sm border border-zinc-800 bg-zinc-950 p-4 flex flex-col gap-4">
      <div className="flex items-center justify-between gap-4">
        <div className="flex items-center gap-2">
          <Sparkles className="size-4 text-fg" />
          <h3 className="text-sm font-semibold text-fg">AI Trade Review</h3>
        </div>
        <Button
          size="sm"
          variant="secondary"
          onClick={generateReview}
          loading={loading}
          disabled={loading}
          className="shrink-0"
        >
          {review ? (
            <>
              <RefreshCw className="size-4" />
              Regenerate
            </>
          ) : (
            <>
              <Sparkles className="size-4" />
              Generate Review
            </>
          )}
        </Button>
      </div>

      {error && (
        <div className="rounded-sm bg-red-500/5 border border-red-500/20 p-3 text-sm text-red-500 flex items-start gap-2">
          <AlertCircle className="size-4 shrink-0 mt-0.5" />
          {error}
        </div>
      )}

      {review ? (
        <div className="flex flex-col gap-3">
          <div
            className={cn(
              'prose prose-sm max-w-none dark:prose-invert',
              'text-fg [&_h2]:text-base [&_h2]:font-semibold [&_h2]:mt-4 [&_h2]:mb-2',
              '[&_ul]:list-disc [&_ul]:pl-5 [&_li]:mb-1',
              '[&_p]:text-sm [&_p]:leading-[1.4] [&_p]:text-fg-subtle'
            )}
            dangerouslySetInnerHTML={{ __html: markdownToHtml(review) }}
          />
          {modelId && (
            <p className="text-xs text-fg-muted">
              Generated by <span className="font-medium text-fg-subtle">{modelId}</span>
            </p>
          )}
        </div>
      ) : (
        <p className="text-sm text-fg-subtle">
          Get a concise post-trade breakdown: execution grade, risk management notes,
          process observations, and one action item for next time.
        </p>
      )}
    </div>
  );
}

function markdownToHtml(md: string): string {
  return md
    .replace(/^### (.*$)/gim, '<h3>$1</h3>')
    .replace(/^## (.*$)/gim, '<h2>$1</h2>')
    .replace(/^# (.*$)/gim, '<h1>$1</h1>')
    .replace(/^\*\*(.*)\*\*/gim, '<strong>$1</strong>')
    .replace(/^\* (.*$)/gim, '<ul><li>$1</li></ul>')
    .replace(/\n/g, '<br />');
}
